package com.ejjiu.image.enums;

/**
 *
 * 创建人  liangsong
 * 创建时间 2019/10/23 18:21
 */
public enum ConfigType {
    
    
    TAB_SELECT_INDEX,
    
    GLOBAL_GIT_BASH_PATH,
    
   
    IMAGE_RELATE_INDEX,
    SPLASH_STORE_FOLDER,
    
    ICON_IMAGES,
    ICON_PLATFORM_IOS,
    ICON_PLATFORM_ANDROID,
    ICON_PLATFORM_PHONEGAP,
    ICON_PLATFORM_WEBAPP,
    ICON_PLATFORM_MAC,
    ICON_PLATFORM_I_WATCH,
    ICON_PLATFORM_WINDOWS_PHONE,
    ICON_PLATFORM_QUASAR,
    ICON_PLATFORM_ICO,
    
    ICON_SIZE_OLD,
    ICON_SIZES_CUSTOM,
    ICON_BACKGROUND_COLOR,
 
    ICON_FILE_PATH,
    ICON_ADD_BADGE,
    ICON_VERSION_BG,
    ICON_VERSION_TEXT,
    ICON_VERSION_NUMBER,
    ICON_ANDROID_FOLDER,
    ICON_ANDROID_FOLDER_TYPE,
    ICON_CONNER_PERCENT,
    ICON_MARGIN_PERCENT,
    ICON_IMAGE_TYPE,
    ICON_CONNER_MARKER_TYPE,
    ICON_CONNER_MARKER_COLOR,
 
    ICON_GENERATE_FOLDER,
    ICON_PREVIEW_SIZE,
    ICON_PREVIEW_SCALE,
    ICON_PREVIEW_UP,
    ICON_CUSTOM_PREFIX,
    ;
}
